---
- hosts: RPi2
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
#    - vagrant_local
    - nginx
#    - rabbitmq
    - php
    - composer
    - app
- hosts: RPi3
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - mysql
    - elasticsearch
