---
- hosts: pi[0:4]
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
#    - vagrant_local
    - nginx
#    - rabbitmq
    - php
    - composer
    - app
- hosts: pi[5:7]
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - mysql
    - elasticsearch
